<a href="https://colab.research.google.com/github/sdivyadarshini29-coder/DATA-SCIENCE-INTERNSHIP/blob/main/fetch_california_housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================
# RANDOM FOREST CLASSIFIER USING
# CALIFORNIA HOUSING DATASET
# ============================================

# 1. Import Libraries
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 2. Load Dataset
housing = fetch_california_housing()

# Convert to DataFrame
df = pd.DataFrame(housing.data, columns=housing.feature_names)

# Add target column
df['MedHouseVal'] = housing.target

# 3. Convert Continuous Target into Categories
# RandomForestClassifier requires categorical labels.
# Here we split house values into 3 classes:
# 0 = Low Price
# 1 = Medium Price
# 2 = High Price
df['Price_Category'] = pd.qcut(
    df['MedHouseVal'],
    q=3,
    labels=[0, 1, 2]
)

# 4. Display First 5 Rows
print("First 5 Rows of Dataset:")
print(df.head())

# 5. Define Features and Target
X = df.drop(['MedHouseVal', 'Price_Category'], axis=1)
y = df['Price_Category']

# 6. Split the Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# 7. Create Random Forest Classifier
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# 8. Train the Model
model.fit(X_train, y_train)

# 9. Make Predictions
y_pred = model.predict(X_test)

# 10. Evaluate the Model
print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 11. Feature Importance
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importance:")
print(feature_importance)

# 12. Predict a New Sample
new_sample = pd.DataFrame([X.iloc[0]])

prediction = model.predict(new_sample)

# Class Labels
class_names = {
    0: "Low Price",
    1: "Medium Price",
    2: "High Price"
}

print("\nPredicted Class:", prediction[0])
print("Predicted Category:", class_names[int(prediction[0])])
print("Actual Class:", y.iloc[0])
print("Actual Category:", class_names[int(y.iloc[0])])

First 5 Rows of Dataset:
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal Price_Category  
0    -122.23        4.526              2  
1    -122.22        3.585              2  
2    -122.24        3.521              2  
3    -122.25        3.413              2  
4    -122.25        3.422              2  

Accuracy Score:
0.8112887596899225

Confusion Matrix:
[[1203  161   14]
 [ 178 1033  179]
 [  26  221 1113]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.87      0.86      1378
           1     